### ISSUE TITLE
classDB method required for loading a plan

### ISSUE THREAD

**Issue by SamuelEllertson** [kkevlar/section-searcher#103]
Need ClassDB method that can take a course object with a null sections list and return a list of sections for that course

**Comment by kkevlar** [comment]
@SamuelEllertson 

It might be a better decision for this method to take a string of a course name and for the ClassDB method to construct / return a constructed class with full sections. 

This may be able to implement a factory pattern if we call ClassDB a ClassFactory or have a class factory use a method with this functionality. #67 #80 

```java 
Course courseInflate(String name)
```

The plan loader can then use a method with this footprint.

**Comment by bwlyday** [comment]
Method signature is "public Course getCourse(String courseName)"
It searches through the a ClassDB object's list of courses for a course with a matching name and returns it.
