### ISSUE TITLE
Nullpointerexception possible in Section class

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#107]
https://sonarcloud.io/project/issues?id=my%3Akkevlar_section-searcher&open=AWq98w8fbVBTIP9I0yFU&resolved=false&types=BUG

![Screenshot from 2019-05-17 14-38-03](https://user-images.githubusercontent.com/10334426/57957521-66c14f00-78b1-11e9-982d-56a4e58d255f.png)

**Comment by bwlyday** [comment]
There is now a null check before it.
