### ISSUE TITLE
SavePlan needs to call isPresent() before calling get()

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#108]
https://sonarcloud.io/project/issues?id=my%3Akkevlar_section-searcher&open=AWq98w8fbVBTIP9I0yFU&resolved=false&types=BUG
![Screenshot from 2019-05-17 14-39-02](https://user-images.githubusercontent.com/10334426/57957553-86f10e00-78b1-11e9-849c-ed480cc2db9a.png)

**Comment by SamuelEllertson** [comment]
Fixed
