### ISSUE TITLE
Error messages must clearly describe the given error.

### ISSUE THREAD

**Issue by aegarro** [kkevlar/section-searcher#116]
In Time.java, line 13 throws an error of "Minutes must be less than 60 or greater than or equal to 0", yet the if statement is if(minutes >= 60 || minutes < 0). So if minutes = 0, an error would be throne yet the message states that it would not.

**Comment by kkevlar** [comment]
Inspection Bug. @bwlyday

**Comment by kkevlar** [comment]
#84

**Comment by bwlyday** [comment]
This is false. It works just fine.
