### ISSUE TITLE
Main.java needs to be separated and moved new child classes into own directory

### ISSUE THREAD

**Issue by thearod5** [kkevlar/section-searcher#120]
First, Main.java contains all GUI information, which needs to be split into separate classes.

Second, there classes created from above should all be moved into a different directory other than "logic".

**Comment by kkevlar** [comment]
> there classes created from above should all be moved into a different directory other than "logic".

@thearod5 if we are not using a specific design pattern, why would this be necessary?

**Comment by kkevlar** [comment]
#84

**Comment by kkevlar** [comment]
Closes #97 and theres no need to split the logic over many classes once main.java is named to Gui or something.java
