### ISSUE TITLE
Acceptance testing from Justin

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#122]
#89

**Comment by JustinPrivitera** [comment]
File to be found in shared google drive folder.

**Comment by kkevlar** [comment]
https://docs.google.com/document/d/1YoqLybHenwdhd1P_S9YjcZS_s1cjtp1Ok7owCD5wdMk/edit?usp=sharing

**Comment by kkevlar** [comment]
Please follow the format of the other acceptance testing outputs as can be seen [here](https://docs.google.com/document/d/19A1v423lrdu5tGjVJE88OTorYQ-Q7CNEJEVczGGFVpw/edit?usp=sharing)

**Comment by kkevlar** [comment]
Acceptance Test: Find a Class
The user shall input their availability as well as class specifications, including 
Time of day
Day of the week
Waitlist length
Whether it is open or closed
Requirement it satisfies
Polyratings of professors
The system shall query the Cal Poly Schedules Database for up to date information on the criteria mentioned in step 1. FAIL
The system shall query the Polyratings Database for up to date information on professor ratings. FAIL
The system shall sort classes based on the criteria the user specified. FAIL
The user shall select classes from the sorted list and add them to their plan.

Extensions:
2. a. The Cal Poly Schedules Database is down or unavailable: The system shall use the last data it collected in place of current data. Go to step 3.
3. a. The Polyratings Database is down or unavailable: The system shall use the last data it collected in place of current data. Go to step 4.

Also copied on to page 2 of the original doc
