### ISSUE TITLE
Acceptance testing from Brandon

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#125]
#89

**Comment by bwlyday** [comment]
Link to my Acceptance Testing Google Doc:
https://docs.google.com/document/d/1Ob2htURhwA7S0fPjH4hT9lXB2bTHKSDBcoQwvvdkDGw/edit?usp=sharing

**Comment by kkevlar** [comment]
Access denied :(

**Comment by kkevlar** [comment]
Please follow the format of the other acceptance testing outputs as can be seen [here](https://docs.google.com/document/d/19A1v423lrdu5tGjVJE88OTorYQ-Q7CNEJEVczGGFVpw/edit?usp=sharing)

**Comment by kkevlar** [comment]
Use Case (internal steps): Provide Preferences
1. The system retrieves class information from Cal Poly DB via UC Find Classes. PASS
2. The student sets their availability for the week. 
3. The system filters out classes that do not match their availability. FAIL
4. The student selects their degree.
5. The system filters out classes that do not contribute to their degree progress. FAIL
6. The student selects a class department.
7. The system filters out classes that are not part of that department. FAIL
8. The student sets a maximum waitlist length.
9. The system filters out classes that have a waitlist longer than the set amount. FAIL
10. The student selects a GE category.
11. The system filters out classes that do not satisfy that GE category. FAIL
12. The student chooses to see only see open classes.
13. The system filters out closed classes. FAIL

Extensions:
1a. Cal Poly DB does not respond: The system notifies the student and terminates the use case. 
2a. The student does not set their availability: The system disregards the classes’ day and time when filtering. Go to step 4.
4a. The student does not select a degree: The system disregards contribution to degree progress when filtering. Go to step 6.
6a. The student does not select a department: The system disregards the classes’ department when filtering. Go to step 8.
8a. The student does not set a maximum waitlist length: The system disregards the classes’ waitlist length when filtering. Go to step 10.
8b. The student enters a negative waitlist length: The system assumes a waitlist length of zero and filters accordingly. Go to step 10.
10a. The student does not select a GE category: The system disregards satisfaction of a GE category when filtering. Go to step 12.
12a. The student does not choose to only see open classes: The system shows open and closed classes.

**Comment by kkevlar** [comment]
https://docs.google.com/document/d/1tQu2YJyBv3odMQYuz-dnm8yf0indtdp3BMneaZNRtDU/edit?usp=sharing
