### ISSUE TITLE
Class search by department

### ISSUE THREAD

**Issue by Jdatechong** [kkevlar/section-searcher#14]
The system shall provide a field for the user to search for all classes under a specific department.

**Comment by kkevlar** [comment]
This requirement should not have mentioned a "field".

Instead the `ClassDB` class (or whatever we call it) should populate / return a data structure of classes matching some String

**Comment by bwlyday** [comment]
ClassDB can return a filtered version of a List\<Course\> object, filtered by String department

**Comment by bwlyday** [comment]
Functions that return a List of sections filtered by department is in ClassDB

**Comment by kkevlar** [comment]
I think this is finsihed........
