### ISSUE TITLE
Make DB class a singleton

### ISSUE THREAD

**Issue by SamuelEllertson** [kkevlar/section-searcher#146]
#80 #67

**Comment by kkevlar** [comment]
[Design Patterns ppt](https://polylearn.calpoly.edu/AY_2018-2019/mod/resource/view.php?id=340132)

**Comment by kkevlar** [comment]
![Screenshot from 2019-05-28 15-36-55](https://user-images.githubusercontent.com/10334426/58516919-71f06680-815e-11e9-90fd-e39dc2a9cbc3.png)

**Comment by kkevlar** [comment]
![Screenshot from 2019-05-28 15-37-32](https://user-images.githubusercontent.com/10334426/58516944-87fe2700-815e-11e9-83cb-f3c2c04c5b67.png)
