### ISSUE TITLE
PlanFactory needs to be used somewhere

### ISSUE THREAD

**Issue by SamuelEllertson** [kkevlar/section-searcher#147]
#67 #80

**Comment by kkevlar** [comment]
Also it has code smells cuz empty

**Comment by kkevlar** [comment]
[Design Patterns ppt](https://polylearn.calpoly.edu/AY_2018-2019/mod/resource/view.php?id=340132)

**Comment by SamuelEllertson** [comment]
Planfactory will be used primarily by the GUI controller to load and save classes

**Comment by kkevlar** [comment]
@jacobrakestraw  are you working on this tonight?
