### ISSUE TITLE
Schedule save function

### ISSUE THREAD

**Issue by Jdatechong** [kkevlar/section-searcher#15]
The system shall save the user’s current class selection every time the user presses the “save selection” button.

**Comment by kkevlar** [comment]
This feature is not trivial and we might choose not to implement it before the demo milestone.

We will need to save the user's plans to a file, preserving the data structures.

We can write our own save/write to file, but it may be better to use "java object serialization" or "java object to XML" strategies instead.

**Comment by kkevlar** [comment]
It may be worthwhile to try working with [JAXB](https://howtodoinjava.com/jaxb/write-object-to-xml/) so that a list of plans gets saved and each of the nested classes' information gets saved

**Comment by kkevlar** [comment]
Replace Main.java with
```java
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;

public class Main {

	public static void main(String[] args) throws JAXBException 
	{
		JAXBContext jaxbContext     = JAXBContext.newInstance( Plan.class );
		Marshaller jaxbMarshaller   = jaxbContext.createMarshaller();

	}

}
```

**Comment by kkevlar** [comment]
Going to need to follow [this tutorial](https://howtodoinjava.com/jaxb/write-object-to-xml/) and annotate the data entities and it should be relatively painless

**Comment by kkevlar** [comment]
I think these should be in the XML saved file:
* Plan or list of plans
* Categories within plans
* Classes in categories (code or id only)

These should not be saved to XML: (probably)
* \*Factory
* Sections
* ClassDB

**Comment by SamuelEllertson** [comment]
full save plan functionality has been added. Planfactory.SavePlan(Plan plan) will save a given plan, PlanFactory.GetPlan(String name) will give you an Optional\<Plan\>, PlanFactory.DeletePlan(String name) will delete a saved plan, and PlanFactory.GetPlanList() will give you an ArrayList of strings of plan names that can be passed to GetPlan(). Plans are saved to the saved_plans folder in the primary directory.
