### ISSUE TITLE
Implement courses to set their department

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#163]
Courses currently do not set their own department field.

![Screenshot from 2019-05-29 15-02-37](https://user-images.githubusercontent.com/10334426/58594553-cfe68200-8222-11e9-925e-390fdd598b91.png)

Fixing this should allow fix of #161 to support development of #151

**Comment by kkevlar** [comment]
Most constructors set department to `""`


![Screenshot from 2019-05-29 15-07-41](https://user-images.githubusercontent.com/10334426/58594796-8cd8de80-8223-11e9-992e-d08284833e95.png)

**Comment by kkevlar** [comment]
@bwlyday says no particular reason why this was done (sonarcloud or otherwise) so should just fix asap

**Comment by kkevlar** [comment]
@jacobrakestraw should be implementing it right now

**Comment by jacobrake** [comment]
Closed in commit 07017e5
