### ISSUE TITLE
Need one activity diagram per member

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#165]
#71

**Comment by kkevlar** [comment]
@SamuelEllertson : #166
@kkevlar : #167
@JustinPrivitera : #168
@jacobrakestraw : #169
@Jdatechong : #170
@bwlyday : #171

**Comment by kkevlar** [comment]
put in this folder https://drive.google.com/drive/folders/1w_2l-g7B8nrGTqnCk7qoBbRh-DRQknb0?usp=sharing

**Comment by bwlyday** [comment]
Provide Preferences Activity Diagram is mine

**Comment by bwlyday** [comment]
Closed the wrong issue

**Comment by JustinPrivitera** [comment]
Kevin says I can close this.

**Comment by JustinPrivitera** [comment]
thanks Kevin
