### ISSUE TITLE
GUI requirements: Needs Plan, Categories, and Section Lists

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#39]
![IMG_20190429_145045](https://user-images.githubusercontent.com/10334426/56929533-b836a500-6a8e-11e9-94ef-1d4379976375.jpg)

**Comment by jacobrakestraw** [comment]
<img width="1430" alt="Screen Shot 2019-05-01 at 3 06 33 PM" src="https://user-images.githubusercontent.com/46944076/57045552-ce756a00-6c22-11e9-816a-b754fdf68765.png">
Demo GUI with dummy data
