### ISSUE TITLE
Parse html from schedules.calpoly.edu

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#45]
To support #7, after downloading / scraping the relevant listing from schedules.calpoly.edu, the system should parse the html to get waitlist information

**Comment by JustinPrivitera** [comment]
Expecting CSV's, not html. Need to work on converting html tables to csv.

**Comment by JustinPrivitera** [comment]
[justins_stuff.zip](https://github.com/kkevlar/section-searcher/files/3150038/justins_stuff.zip)
