### ISSUE TITLE
Remove "department" field from course entity

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#61]

**Comment by bwlyday** [comment]
This shouldn't be done. It will break the methods in ClassDB that rely on the department field for sorting and filtering

**Comment by SamuelEllertson** [comment]
While redundant, there's no pressing reason to take it out if the DB sorting stuff relies on it. A course entity can keep both the name "CSC309" and have a department string, but that means that we need logic to handling that parsing.
