### ISSUE TITLE
Highlight not implemented requirements

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#78]

**Comment by kkevlar** [comment]
The system shall display whether each class on a given list currently has available sections. (edited: period added)
The system shall allow [1,100] classes per category in the plan. (edited: “per category in the plan” was instead “on the search list”)
The system shall provide ability to sort the class list by shortest waitlist.
The system shall gather the times and days of the week for each class from schedules.calpoly.edu, and store the information.
The system shall generate a filtered list of classes based on any combination of the following criteria, with combinations selected by the user: (edited: used to say “sorted list” but it was unclear by what metric the list was sorted)
Time of day
Day of the week
Waitlist length
Whether it is open or closed
Requirement it satisfies
The system shall display up-to-date information about waitlists, course availability, and course schedules.
The system shall provide the polyrating score of each professor for all listed classes if available.
The system shall provide only classes that do not conflict with the entered schedule.
The system shall provide a visual representation of potential schedules.
The system shall show all classes available for a given quarter in a specific GE category.
The system shall show all open classes that count toward the user’s degree progress in a given quarter.
The system shall show all open classes that match the user’s availability.
The system shall allow the user to search for a single class by name. (edited: removed mention of a “search bar”)
The system shall provide a list of all classes under a specific department when prompted. (edited: removed reference to a search field)
The system shall save user’s current class selection. (edited: removed reference to a button)

**Comment by Jdatechong** [comment]
https://docs.google.com/document/d/1dkNF7WA5ZsmJ1Yiir-oKL3VbuBHWOxzLCQgMsrdQkPM/edit#
