### ISSUE TITLE
Design \ Code Fragment Final Requirements

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#79]
It is required to provide one code fragment per each type of design deliverable: 

When making these code snippets, comment that the snippet shouldn't be deleted

* patterns #80
* sequence diagram #81
* activity diagram #82
* state diagram #83

**Comment by JustinPrivitera** [comment]
<img width="431" alt="fragment" src="https://user-images.githubusercontent.com/35237779/58995358-c3c16e00-87a8-11e9-8bee-8c37303f4d0a.png">

**Comment by JustinPrivitera** [comment]
![HW2](https://user-images.githubusercontent.com/35237779/58995370-ccb23f80-87a8-11e9-9a38-04441e53219f.jpg)

**Comment by SamuelEllertson** [comment]
[Code snippets.pdf](https://github.com/kkevlar/section-searcher/files/3259328/Code.snippets.pdf)

its also in shared folder
