### ISSUE TITLE
Need two code fragments for design patterns

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#80]
Needs #67

**Comment by kkevlar** [comment]
[Design Patterns ppt](https://polylearn.calpoly.edu/AY_2018-2019/mod/resource/view.php?id=340132)

**Comment by SamuelEllertson** [comment]
from PlanFactory
![image](https://user-images.githubusercontent.com/28110981/58517885-d2cd6e00-8161-11e9-8c82-3aa06858647d.png)

**Comment by SamuelEllertson** [comment]
from ClassDB (singleton)
![image](https://user-images.githubusercontent.com/28110981/58737291-cc373480-83b5-11e9-87cb-b16cd90354e1.png)
