### ISSUE TITLE
Code fragment: activity diagram

### ISSUE THREAD

**Issue by kkevlar** [kkevlar/section-searcher#82]

**Comment by SamuelEllertson** [comment]
Implements "edit schedule" activity diagram
![image](https://user-images.githubusercontent.com/28110981/58738496-e1629200-83ba-11e9-9b46-7ebdafd49e58.png)
![image](https://user-images.githubusercontent.com/28110981/58738514-ea536380-83ba-11e9-9ddd-e97cffa25bf0.png)
